# permissions for end users to edit nginxdeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxdeploy-editor-role
rules:
- apiGroups:
  - batch.my.domain
  resources:
  - nginxdeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.my.domain
  resources:
  - nginxdeploys/status
  verbs:
  - get
