# permissions for end users to view nginxdeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxdeploy-viewer-role
rules:
- apiGroups:
  - batch.my.domain
  resources:
  - nginxdeploys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.my.domain
  resources:
  - nginxdeploys/status
  verbs:
  - get
